#!/bin/bash 

# git status
git status -s 

echo
echo '#########################################'
echo '########## EDITS UNSTAGED ###############'
echo '#########################################'
echo 

# git diff 
git diff --stat 

echo
echo '#########################################'
echo '############## STAGED ###################'
echo '#########################################'
echo 

git diff --staged 


